/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author luisr
 */
public class PanelInventario extends javax.swing.JPanel {

    /**
     * Creates new form PanelInventario
     */
    public PanelInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarMedicamento = new javax.swing.JLabel();
        consultarMedicamento = new javax.swing.JLabel();
        agregarMedicamento = new javax.swing.JLabel();
        iconoUsuario = new javax.swing.JLabel();
        medicamentosTitulo = new javax.swing.JLabel();
        medicamentosSubtitulo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminarBoton.png"))); // NOI18N
        eliminarMedicamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(eliminarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 317, -1, -1));

        consultarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consultarBoton.png"))); // NOI18N
        consultarMedicamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarMedicamentoMouseClicked(evt);
            }
        });
        add(consultarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 105, -1, -1));

        agregarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregarBoton.png"))); // NOI18N
        agregarMedicamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMedicamentoMouseClicked(evt);
            }
        });
        add(agregarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 105, -1, -1));

        iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User.png"))); // NOI18N
        add(iconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 60, 50));

        medicamentosTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inventario.png"))); // NOI18N
        add(medicamentosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 40));

        medicamentosSubtitulo.setFont(new java.awt.Font("Hind Medium", 0, 14)); // NOI18N
        medicamentosSubtitulo.setForeground(new java.awt.Color(109, 127, 136));
        medicamentosSubtitulo.setText("Presione para modificar");
        add(medicamentosSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void consultarMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMedicamentoMouseClicked
        Dashboard.ShowJPanel(new PanelConsultarMedicamentos());
    }//GEN-LAST:event_consultarMedicamentoMouseClicked

    private void agregarMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMedicamentoMouseClicked
        Dashboard.ShowJPanel(new PanelAgregarMedicamento());
    }//GEN-LAST:event_agregarMedicamentoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarMedicamento;
    private javax.swing.JLabel consultarMedicamento;
    private javax.swing.JLabel eliminarMedicamento;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JLabel medicamentosSubtitulo;
    private javax.swing.JLabel medicamentosTitulo;
    // End of variables declaration//GEN-END:variables
}
